version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/resume/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
